development:  
  DATABASE_USERNAME: 'reza'  
  DATABASE_PASSWORD: '147147'

test:  
  DATABASE_USERNAME: 'reza'  
  DATABASE_PASSWORD: '147147'

production:  
  DATABASE_USERNAME: 'postgres'  
  DATABASE_PASSWORD: 'postgres'  
  AWS_ACCESS_KEY_ID: 'AKIAJ7K673M4YQXQ4WWA'  
  AWS_SECRET_ACCESS_KEY: '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'